### ISSUE TITLE
Are the documentation update?

### ISSUE THREAD

**Issue by eponcehenriquez** [AnowarCST/laravel-vue-crud-starter#25]
I followed the installation as indicated in the documentation, unfortunately throws an error GET http://localhost:8888/css/app.css net::ERR_ABORTED 404 (Not Found) AdminLTE.css.map:13.

Also look for the adminlte (almasaeed2010/adminlte) folder in Vendor and I did not find it, 
Finally the configuration file (AdminLTE.php) in the config folder is not found.

great job. regards

**Comment by AnowarCST** [comment]
> I followed the installation as indicated in the documentation, unfortunately throws an error GET http://localhost:8888/css/app.css net::ERR_ABORTED 404 (Not Found) AdminLTE.css.map:13.
> 
> Also look for the adminlte (almasaeed2010/adminlte) folder in Vendor and I did not find it,
> Finally the configuration file (AdminLTE.php) in the config folder is not found.
> 
> great job. regards

Can you please provide some details about your server information with versions?

**Comment by AnowarCST** [comment]
How do you tried and what is your environment?

**Comment by eponcehenriquez** [comment]
Dear, install via composer in Mac and Windows.

**Comment by eponcehenriquez** [comment]
solved thanks
