### ISSUE TITLE
Is there a way to do Search Filters? I can't seem to execute any search function in controller

### ISSUE THREAD

**Issue by geeksified** [AnowarCST/laravel-vue-crud-starter#39]
Hi. I tried adding a search function in the user controller and render it in vue using v-model but it always calls the function index(). It won't call what's inside the public function search () even though I added the search in route::get

I also tried following the Youtube video from Code Inspire but it still doesn't work. It always executes the index().

Thank you.

**Comment by AnowarCST** [comment]
Not sure which index() you are mentioning.
