### ISSUE TITLE
adminer connection issue

### ISSUE THREAD

**Issue by iamraju** [AnowarCST/laravel-vue-crud-starter#52]
Hi There,

What are the correct credentials for logging into adminer ? I tried with :
host: db:3307
user: root
password: 123456

But it does not work, it always says connection refused.

**Comment by AnowarCST** [comment]
Please Try: 
DB-host: yourIP:3307
User: root
Password: 123456

**Comment by iamraju** [comment]
Well since I am new to docker thing, I am not sure how do I get my IP address, can you help please ?

**Comment by AnowarCST** [comment]
Check your network property to get your machine IP. This is not the docker IP.
