### ISSUE TITLE
Standard User is able to Create Oauth Clients and Access Tokens

### ISSUE THREAD

**Issue by krebbi** [AnowarCST/laravel-vue-crud-starter#55]
A Standard User is able to open /settings/developer and create OAuth clients as well as Personal Access Tokens.
He can also visit all /other settings pages, but don't get any further information.

The Routes to /settings (admin area) do need some protection.

**Comment by John94php** [comment]
maybe via Gate or middleware

**Comment by John94php** [comment]
e.g 
```
        if (!Gate::allows('isAdmin')) {
            return $this->unauthorizedResponse();
        }

```
