### ISSUE TITLE
IT HAS POSTINSTALL.JS VIRUS

### ISSUE THREAD

**Issue by nasirdavinci** [AnowarCST/laravel-vue-crud-starter#64]

**Comment by gmizaelmtzhdz** [comment]
Hi @nasirdavinci , what do you mean? Would you explain more about this issue? I want to use this template but now I am interesting in this open issue

**Comment by gmizaelmtzhdz** [comment]
Oh that's bad. @AnowarCST What do you think? 
is it a vulnerable dependency of nodejs?

**Comment by AnowarCST** [comment]
@gmizaelmtzhdz @nasirdavinci I don't think so. Let me check this issue. Thank you for the information.
